
import { Raleway } from 'next/font/google'
import "./globals.css";
import LinksFooter from "@/components/LinksFooter/LinksFooter";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'], // Choose the weights you need
  variable: '--font-raleway', // Optional: define a CSS variable
})

 
export default function RootLayout({ children }) {
 return (
    <html lang="es" className={raleway.variable}>
      <body>
        <main>

          {children} 
          <LinksFooter />

        </main>
      </body>
    </html>
  )
}
