import "./globals.css";
import LinksFooter from "@/components/LinksFooter/LinksFooter";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <main>

          {children} 
          <LinksFooter />

        </main>
      </body>
    </html>
  )
}
